-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.BikePark exposing (id, latitude, longitude, name, realtime, selection, spacesAvailable)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.BikePark
selection constructor =
    Object.selection constructor


id : Field Entur.Scalar.Id Entur.Object.BikePark
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Id)


name : Field String Entur.Object.BikePark
name =
    Object.fieldDecoder "name" [] Decode.string


spacesAvailable : Field (Maybe Int) Entur.Object.BikePark
spacesAvailable =
    Object.fieldDecoder "spacesAvailable" [] (Decode.int |> Decode.nullable)


realtime : Field (Maybe Bool) Entur.Object.BikePark
realtime =
    Object.fieldDecoder "realtime" [] (Decode.bool |> Decode.nullable)


longitude : Field (Maybe Float) Entur.Object.BikePark
longitude =
    Object.fieldDecoder "longitude" [] (Decode.float |> Decode.nullable)


latitude : Field (Maybe Float) Entur.Object.BikePark
latitude =
    Object.fieldDecoder "latitude" [] (Decode.float |> Decode.nullable)
