-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.BikeRentalStation exposing (allowDropoff, bikesAvailable, description, id, latitude, longitude, name, networks, realtimeOccupancyAvailable, selection, spacesAvailable)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.BikeRentalStation
selection constructor =
    Object.selection constructor


id : Field Entur.Scalar.Id Entur.Object.BikeRentalStation
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Id)


name : Field String Entur.Object.BikeRentalStation
name =
    Object.fieldDecoder "name" [] Decode.string


description : Field (Maybe String) Entur.Object.BikeRentalStation
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


bikesAvailable : Field (Maybe Int) Entur.Object.BikeRentalStation
bikesAvailable =
    Object.fieldDecoder "bikesAvailable" [] (Decode.int |> Decode.nullable)


spacesAvailable : Field (Maybe Int) Entur.Object.BikeRentalStation
spacesAvailable =
    Object.fieldDecoder "spacesAvailable" [] (Decode.int |> Decode.nullable)


realtimeOccupancyAvailable : Field (Maybe Bool) Entur.Object.BikeRentalStation
realtimeOccupancyAvailable =
    Object.fieldDecoder "realtimeOccupancyAvailable" [] (Decode.bool |> Decode.nullable)


allowDropoff : Field (Maybe Bool) Entur.Object.BikeRentalStation
allowDropoff =
    Object.fieldDecoder "allowDropoff" [] (Decode.bool |> Decode.nullable)


networks : Field (List (Maybe String)) Entur.Object.BikeRentalStation
networks =
    Object.fieldDecoder "networks" [] (Decode.string |> Decode.nullable |> Decode.list)


longitude : Field (Maybe Float) Entur.Object.BikeRentalStation
longitude =
    Object.fieldDecoder "longitude" [] (Decode.float |> Decode.nullable)


latitude : Field (Maybe Float) Entur.Object.BikeRentalStation
latitude =
    Object.fieldDecoder "latitude" [] (Decode.float |> Decode.nullable)
