-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.Contact exposing (contactPerson, email, furtherDetails, phone, selection, url)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.Contact
selection constructor =
    Object.selection constructor


{-| Name of person to contact
-}
contactPerson : Field (Maybe String) Entur.Object.Contact
contactPerson =
    Object.fieldDecoder "contactPerson" [] (Decode.string |> Decode.nullable)


{-| Email adress for contact
-}
email : Field (Maybe String) Entur.Object.Contact
email =
    Object.fieldDecoder "email" [] (Decode.string |> Decode.nullable)


{-| Url for contact
-}
url : Field (Maybe String) Entur.Object.Contact
url =
    Object.fieldDecoder "url" [] (Decode.string |> Decode.nullable)


{-| Phone number for contact
-}
phone : Field (Maybe String) Entur.Object.Contact
phone =
    Object.fieldDecoder "phone" [] (Decode.string |> Decode.nullable)


{-| Textual description of how to get in contact
-}
furtherDetails : Field (Maybe String) Entur.Object.Contact
furtherDetails =
    Object.fieldDecoder "furtherDetails" [] (Decode.string |> Decode.nullable)
