-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.Interchange exposing (fromLine, fromServiceJourney, guaranteed, selection, staySeated, toLine, toServiceJourney)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.Interchange
selection constructor =
    Object.selection constructor


{-| Time that the trip departs.
-}
staySeated : Field (Maybe Bool) Entur.Object.Interchange
staySeated =
    Object.fieldDecoder "staySeated" [] (Decode.bool |> Decode.nullable)


{-| Time that the trip departs.
-}
guaranteed : Field (Maybe Bool) Entur.Object.Interchange
guaranteed =
    Object.fieldDecoder "guaranteed" [] (Decode.bool |> Decode.nullable)


fromLine : SelectionSet decodesTo Entur.Object.Line -> Field (Maybe decodesTo) Entur.Object.Interchange
fromLine object_ =
    Object.selectionField "FromLine" [] object_ (identity >> Decode.nullable)


toLine : SelectionSet decodesTo Entur.Object.Line -> Field (Maybe decodesTo) Entur.Object.Interchange
toLine object_ =
    Object.selectionField "ToLine" [] object_ (identity >> Decode.nullable)


fromServiceJourney : SelectionSet decodesTo Entur.Object.ServiceJourney -> Field (Maybe decodesTo) Entur.Object.Interchange
fromServiceJourney object_ =
    Object.selectionField "FromServiceJourney" [] object_ (identity >> Decode.nullable)


toServiceJourney : SelectionSet decodesTo Entur.Object.ServiceJourney -> Field (Maybe decodesTo) Entur.Object.Interchange
toServiceJourney object_ =
    Object.selectionField "ToServiceJourney" [] object_ (identity >> Decode.nullable)
