-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.MultilingualString exposing (language, selection, value)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.MultilingualString
selection constructor =
    Object.selection constructor


value : Field (Maybe String) Entur.Object.MultilingualString
value =
    Object.fieldDecoder "value" [] (Decode.string |> Decode.nullable)


language : Field (Maybe String) Entur.Object.MultilingualString
language =
    Object.fieldDecoder "language" [] (Decode.string |> Decode.nullable)
