-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.PlaceAtDistance exposing (distance, id, place, selection)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.PlaceAtDistance
selection constructor =
    Object.selection constructor


id : Field Entur.Scalar.Id Entur.Object.PlaceAtDistance
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Id)


place : SelectionSet decodesTo Entur.Interface.PlaceInterface -> Field (Maybe decodesTo) Entur.Object.PlaceAtDistance
place object_ =
    Object.selectionField "place" [] object_ (identity >> Decode.nullable)


distance : Field (Maybe Int) Entur.Object.PlaceAtDistance
distance =
    Object.fieldDecoder "distance" [] (Decode.int |> Decode.nullable)
