-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.PlaceAtDistanceEdge exposing (cursor, node, selection)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.PlaceAtDistanceEdge
selection constructor =
    Object.selection constructor


{-| The item at the end of the edge
-}
node : SelectionSet decodesTo Entur.Object.PlaceAtDistance -> Field (Maybe decodesTo) Entur.Object.PlaceAtDistanceEdge
node object_ =
    Object.selectionField "node" [] object_ (identity >> Decode.nullable)


{-| cursor marks a unique position or index into the connection
-}
cursor : Field String Entur.Object.PlaceAtDistanceEdge
cursor =
    Object.fieldDecoder "cursor" [] Decode.string
