-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.PointsOnLink exposing (length, points, selection)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.PointsOnLink
selection constructor =
    Object.selection constructor


{-| The number of points in the string
-}
length : Field (Maybe Int) Entur.Object.PointsOnLink
length =
    Object.fieldDecoder "length" [] (Decode.int |> Decode.nullable)


{-| The encoded points of the polyline.
-}
points : Field (Maybe String) Entur.Object.PointsOnLink
points =
    Object.fieldDecoder "points" [] (Decode.string |> Decode.nullable)
