-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.Presentation exposing (colour, selection, textColour)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.Presentation
selection constructor =
    Object.selection constructor


colour : Field (Maybe String) Entur.Object.Presentation
colour =
    Object.fieldDecoder "colour" [] (Decode.string |> Decode.nullable)


textColour : Field (Maybe String) Entur.Object.Presentation
textColour =
    Object.fieldDecoder "textColour" [] (Decode.string |> Decode.nullable)
