-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.PtSituationElement exposing (authority, description, detail, id, infoLink, journeyPatterns, lines, organisation, quays, reportType, selection, serviceJourneys, situationNumber, stopConditions, stopPlaces, summary, validityPeriod)

import Entur.Enum.ReportType
import Entur.Enum.StopCondition
import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.PtSituationElement
selection constructor =
    Object.selection constructor


id : Field Entur.Scalar.Id Entur.Object.PtSituationElement
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Id)


authority : SelectionSet decodesTo Entur.Object.Authority -> Field (Maybe decodesTo) Entur.Object.PtSituationElement
authority object_ =
    Object.selectionField "authority" [] object_ (identity >> Decode.nullable)


organisation : SelectionSet decodesTo Entur.Object.Organisation -> Field (Maybe decodesTo) Entur.Object.PtSituationElement
organisation object_ =
    Object.selectionField "organisation" [] object_ (identity >> Decode.nullable)


lines : SelectionSet decodesTo Entur.Object.Line -> Field (List (Maybe decodesTo)) Entur.Object.PtSituationElement
lines object_ =
    Object.selectionField "lines" [] object_ (identity >> Decode.nullable >> Decode.list)


serviceJourneys : SelectionSet decodesTo Entur.Object.ServiceJourney -> Field (List (Maybe decodesTo)) Entur.Object.PtSituationElement
serviceJourneys object_ =
    Object.selectionField "serviceJourneys" [] object_ (identity >> Decode.nullable >> Decode.list)


quays : SelectionSet decodesTo Entur.Object.Quay -> Field (List (Maybe decodesTo)) Entur.Object.PtSituationElement
quays object_ =
    Object.selectionField "quays" [] object_ (identity >> Decode.nullable >> Decode.list)


stopPlaces : SelectionSet decodesTo Entur.Object.StopPlace -> Field (List (Maybe decodesTo)) Entur.Object.PtSituationElement
stopPlaces object_ =
    Object.selectionField "stopPlaces" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Get all journey patterns for this situation element
-}
journeyPatterns : SelectionSet decodesTo Entur.Object.JourneyPattern -> Field (List (Maybe decodesTo)) Entur.Object.PtSituationElement
journeyPatterns object_ =
    Object.selectionField "journeyPatterns" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Summary of situation in all different translations available
-}
summary : SelectionSet decodesTo Entur.Object.MultilingualString -> Field (List decodesTo) Entur.Object.PtSituationElement
summary object_ =
    Object.selectionField "summary" [] object_ (identity >> Decode.list)


{-| Description of situation in all different translations available
-}
description : SelectionSet decodesTo Entur.Object.MultilingualString -> Field (List decodesTo) Entur.Object.PtSituationElement
description object_ =
    Object.selectionField "description" [] object_ (identity >> Decode.list)


{-| Details of situation in all different translations available
-}
detail : SelectionSet decodesTo Entur.Object.MultilingualString -> Field (List decodesTo) Entur.Object.PtSituationElement
detail object_ =
    Object.selectionField "detail" [] object_ (identity >> Decode.list)


{-| Url with more information
-}
infoLink : Field (Maybe String) Entur.Object.PtSituationElement
infoLink =
    Object.fieldDecoder "infoLink" [] (Decode.string |> Decode.nullable)


{-| Period this situation is in effect
-}
validityPeriod : SelectionSet decodesTo Entur.Object.ValidityPeriod -> Field (Maybe decodesTo) Entur.Object.PtSituationElement
validityPeriod object_ =
    Object.selectionField "validityPeriod" [] object_ (identity >> Decode.nullable)


{-| ReportType of this situation
-}
reportType : Field (Maybe Entur.Enum.ReportType.ReportType) Entur.Object.PtSituationElement
reportType =
    Object.fieldDecoder "reportType" [] (Entur.Enum.ReportType.decoder |> Decode.nullable)


{-| StopConditions of this situation
-}
stopConditions : Field (List (Maybe Entur.Enum.StopCondition.StopCondition)) Entur.Object.PtSituationElement
stopConditions =
    Object.fieldDecoder "stopConditions" [] (Entur.Enum.StopCondition.decoder |> Decode.nullable |> Decode.list)


{-| Operator's internal id for this situation
-}
situationNumber : Field (Maybe String) Entur.Object.PtSituationElement
situationNumber =
    Object.fieldDecoder "situationNumber" [] (Decode.string |> Decode.nullable)
