-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.ServiceJourney exposing (EstimatedCallsOptionalArguments, activeDates, bikesAllowed, bookingArrangements, directionType, estimatedCalls, flexibleServiceType, id, journeyPattern, keyValues, line, linePublicCode, notices, operator, passingTimes, pointsOnLink, privateCode, publicCode, quays, selection, serviceAlteration, situations, transportSubmode, wheelchairAccessible)

import Entur.Enum.BikesAllowed
import Entur.Enum.DirectionType
import Entur.Enum.FlexibleServiceType
import Entur.Enum.ServiceAlteration
import Entur.Enum.TransportSubmode
import Entur.Enum.WheelchairBoarding
import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.ServiceJourney
selection constructor =
    Object.selection constructor


id : Field Entur.Scalar.Id Entur.Object.ServiceJourney
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Id)


line : SelectionSet decodesTo Entur.Object.Line -> Field decodesTo Entur.Object.ServiceJourney
line object_ =
    Object.selectionField "line" [] object_ identity


activeDates : Field (List (Maybe Entur.Scalar.Date)) Entur.Object.ServiceJourney
activeDates =
    Object.fieldDecoder "activeDates" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Date |> Decode.nullable |> Decode.list)


{-| Whether journey is as planned, a cancellation or an extra journey. Default is as planned
-}
serviceAlteration : Field (Maybe Entur.Enum.ServiceAlteration.ServiceAlteration) Entur.Object.ServiceJourney
serviceAlteration =
    Object.fieldDecoder "serviceAlteration" [] (Entur.Enum.ServiceAlteration.decoder |> Decode.nullable)


{-| The transport submode of the journey, if different from lines transport submode.
-}
transportSubmode : Field (Maybe Entur.Enum.TransportSubmode.TransportSubmode) Entur.Object.ServiceJourney
transportSubmode =
    Object.fieldDecoder "transportSubmode" [] (Entur.Enum.TransportSubmode.decoder |> Decode.nullable)


{-| Publicly announced code for service journey, differentiating it from other service journeys for the same line.
-}
publicCode : Field (Maybe String) Entur.Object.ServiceJourney
publicCode =
    Object.fieldDecoder "publicCode" [] (Decode.string |> Decode.nullable)


{-| For internal use by operators.
-}
privateCode : Field (Maybe String) Entur.Object.ServiceJourney
privateCode =
    Object.fieldDecoder "privateCode" [] (Decode.string |> Decode.nullable)


{-| Publicly announced code for line, differentiating it from other lines for the same operator.
-}
linePublicCode : Field (Maybe String) Entur.Object.ServiceJourney
linePublicCode =
    Object.fieldDecoder "linePublicCode" [] (Decode.string |> Decode.nullable)


operator : SelectionSet decodesTo Entur.Object.Operator -> Field (Maybe decodesTo) Entur.Object.ServiceJourney
operator object_ =
    Object.selectionField "operator" [] object_ (identity >> Decode.nullable)


directionType : Field (Maybe Entur.Enum.DirectionType.DirectionType) Entur.Object.ServiceJourney
directionType =
    Object.fieldDecoder "directionType" [] (Entur.Enum.DirectionType.decoder |> Decode.nullable)


{-| Whether service journey is accessible with wheelchair.
-}
wheelchairAccessible : Field (Maybe Entur.Enum.WheelchairBoarding.WheelchairBoarding) Entur.Object.ServiceJourney
wheelchairAccessible =
    Object.fieldDecoder "wheelchairAccessible" [] (Entur.Enum.WheelchairBoarding.decoder |> Decode.nullable)


{-| Whether bikes are allowed on service journey.
-}
bikesAllowed : Field (Maybe Entur.Enum.BikesAllowed.BikesAllowed) Entur.Object.ServiceJourney
bikesAllowed =
    Object.fieldDecoder "bikesAllowed" [] (Entur.Enum.BikesAllowed.decoder |> Decode.nullable)


journeyPattern : SelectionSet decodesTo Entur.Object.JourneyPattern -> Field (Maybe decodesTo) Entur.Object.ServiceJourney
journeyPattern object_ =
    Object.selectionField "journeyPattern" [] object_ (identity >> Decode.nullable)


{-| Quays visited by service journey
-}
quays : SelectionSet decodesTo Entur.Object.Quay -> Field (List decodesTo) Entur.Object.ServiceJourney
quays object_ =
    Object.selectionField "quays" [] object_ (identity >> Decode.list)


{-| Returns scheduled passing times only - without realtime-updates, for realtime-data use 'estimatedCalls'
-}
passingTimes : SelectionSet decodesTo Entur.Object.TimetabledPassingTime -> Field (List (Maybe decodesTo)) Entur.Object.ServiceJourney
passingTimes object_ =
    Object.selectionField "passingTimes" [] object_ (identity >> Decode.nullable >> Decode.list)


type alias EstimatedCallsOptionalArguments =
    { date : OptionalArgument Entur.Scalar.Date }


{-| Returns scheduled passingTimes for this ServiceJourney for a given date, updated with realtime-updates (if available). NB! This takes a date as argument (default=today) and returns estimatedCalls for that date and should only be used if the date is known when creating the request. For fetching estimatedCalls for a given trip.leg, use leg.serviceJourneyEstimatedCalls instead.

  - date - Date to get estimated calls for. Defaults to today.

-}
estimatedCalls : (EstimatedCallsOptionalArguments -> EstimatedCallsOptionalArguments) -> SelectionSet decodesTo Entur.Object.EstimatedCall -> Field (Maybe (List (Maybe decodesTo))) Entur.Object.ServiceJourney
estimatedCalls fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { date = Absent }

        optionalArgs =
            [ Argument.optional "date" filledInOptionals.date (\(Entur.Scalar.Date raw) -> Encode.string raw) ]
                |> List.filterMap identity
    in
    Object.selectionField "estimatedCalls" optionalArgs object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Detailed path travelled by service journey.
-}
pointsOnLink : SelectionSet decodesTo Entur.Object.PointsOnLink -> Field (Maybe decodesTo) Entur.Object.ServiceJourney
pointsOnLink object_ =
    Object.selectionField "pointsOnLink" [] object_ (identity >> Decode.nullable)


notices : SelectionSet decodesTo Entur.Object.Notice -> Field (List (Maybe decodesTo)) Entur.Object.ServiceJourney
notices object_ =
    Object.selectionField "notices" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Get all situations active for the service journey
-}
situations : SelectionSet decodesTo Entur.Object.PtSituationElement -> Field (List (Maybe decodesTo)) Entur.Object.ServiceJourney
situations object_ =
    Object.selectionField "situations" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| List of keyValue pairs for the service journey.
-}
keyValues : SelectionSet decodesTo Entur.Object.KeyValue -> Field (Maybe (List (Maybe decodesTo))) Entur.Object.ServiceJourney
keyValues object_ =
    Object.selectionField "keyValues" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Type of flexible service, or null if service is not flexible.
-}
flexibleServiceType : Field (Maybe Entur.Enum.FlexibleServiceType.FlexibleServiceType) Entur.Object.ServiceJourney
flexibleServiceType =
    Object.fieldDecoder "flexibleServiceType" [] (Entur.Enum.FlexibleServiceType.decoder |> Decode.nullable)


{-| Booking arrangements for flexible services.
-}
bookingArrangements : SelectionSet decodesTo Entur.Object.BookingArrangement -> Field (Maybe decodesTo) Entur.Object.ServiceJourney
bookingArrangements object_ =
    Object.selectionField "bookingArrangements" [] object_ (identity >> Decode.nullable)
