-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.TimeAndDayOffset exposing (dayOffset, selection, time)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.TimeAndDayOffset
selection constructor =
    Object.selection constructor


{-| Local time
-}
time : Field (Maybe Entur.Scalar.Time) Entur.Object.TimeAndDayOffset
time =
    Object.fieldDecoder "time" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Time |> Decode.nullable)


{-| Number of days offset from base line time
-}
dayOffset : Field (Maybe Int) Entur.Object.TimeAndDayOffset
dayOffset =
    Object.fieldDecoder "dayOffset" [] (Decode.int |> Decode.nullable)
