-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Object.ValidityPeriod exposing (endTime, selection, startTime)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Object.ValidityPeriod
selection constructor =
    Object.selection constructor


{-| Start of validity period
-}
startTime : Field (Maybe Entur.Scalar.DateTime) Entur.Object.ValidityPeriod
startTime =
    Object.fieldDecoder "startTime" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.DateTime |> Decode.nullable)


{-| End of validity period
-}
endTime : Field (Maybe Entur.Scalar.DateTime) Entur.Object.ValidityPeriod
endTime =
    Object.fieldDecoder "endTime" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.DateTime |> Decode.nullable)
