-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Entur.Interface.PlaceInterface exposing (commonSelection, id, latitude, longitude, onBikePark, onBikeRentalStation, onCarPark, onQuay, onStopPlace, selection)

import Entur.InputObject
import Entur.Interface
import Entur.Object
import Entur.Scalar
import Entur.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


{-| Select only common fields from the interface.
-}
commonSelection : (a -> constructor) -> SelectionSet (a -> constructor) Entur.Interface.PlaceInterface
commonSelection constructor =
    Object.selection constructor


{-| Select both common and type-specific fields from the interface.
-}
selection : (Maybe typeSpecific -> a -> constructor) -> List (FragmentSelectionSet typeSpecific Entur.Interface.PlaceInterface) -> SelectionSet (a -> constructor) Entur.Interface.PlaceInterface
selection constructor typeSpecificDecoders =
    Object.interfaceSelection typeSpecificDecoders constructor


onStopPlace : SelectionSet decodesTo Entur.Object.StopPlace -> FragmentSelectionSet decodesTo Entur.Interface.PlaceInterface
onStopPlace (SelectionSet fields decoder) =
    FragmentSelectionSet "StopPlace" fields decoder


onQuay : SelectionSet decodesTo Entur.Object.Quay -> FragmentSelectionSet decodesTo Entur.Interface.PlaceInterface
onQuay (SelectionSet fields decoder) =
    FragmentSelectionSet "Quay" fields decoder


onBikeRentalStation : SelectionSet decodesTo Entur.Object.BikeRentalStation -> FragmentSelectionSet decodesTo Entur.Interface.PlaceInterface
onBikeRentalStation (SelectionSet fields decoder) =
    FragmentSelectionSet "BikeRentalStation" fields decoder


onBikePark : SelectionSet decodesTo Entur.Object.BikePark -> FragmentSelectionSet decodesTo Entur.Interface.PlaceInterface
onBikePark (SelectionSet fields decoder) =
    FragmentSelectionSet "BikePark" fields decoder


onCarPark : SelectionSet decodesTo Entur.Object.CarPark -> FragmentSelectionSet decodesTo Entur.Interface.PlaceInterface
onCarPark (SelectionSet fields decoder) =
    FragmentSelectionSet "CarPark" fields decoder


id : Field Entur.Scalar.Id Entur.Interface.PlaceInterface
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map Entur.Scalar.Id)


latitude : Field (Maybe Float) Entur.Interface.PlaceInterface
latitude =
    Object.fieldDecoder "latitude" [] (Decode.float |> Decode.nullable)


longitude : Field (Maybe Float) Entur.Interface.PlaceInterface
longitude =
    Object.fieldDecoder "longitude" [] (Decode.float |> Decode.nullable)
