-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Scalar exposing (Date(..), DateTime(..), Id(..), LocalTime(..), Long(..), Time(..))


type Date
    = Date String


type DateTime
    = DateTime String


type Id
    = Id String


type LocalTime
    = LocalTime String


type Long
    = Long String


type Time
    = Time String
