-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Interface.PlaceInterface exposing (commonSelection, id, latitude, longitude, onBikePark, onBikeRentalStation, onCarPark, onQuay, onStopPlace, selection)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode


{-| Select only common fields from the interface.
-}
commonSelection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Interface.PlaceInterface
commonSelection constructor =
    Object.selection constructor


{-| Select both common and type-specific fields from the interface.
-}
selection : (Maybe typeSpecific -> a -> constructor) -> List (FragmentSelectionSet typeSpecific EnturApi.Interface.PlaceInterface) -> SelectionSet (a -> constructor) EnturApi.Interface.PlaceInterface
selection constructor typeSpecificDecoders =
    Object.interfaceSelection typeSpecificDecoders constructor


onStopPlace : SelectionSet decodesTo EnturApi.Object.StopPlace -> FragmentSelectionSet decodesTo EnturApi.Interface.PlaceInterface
onStopPlace (SelectionSet fields decoder) =
    FragmentSelectionSet "StopPlace" fields decoder


onQuay : SelectionSet decodesTo EnturApi.Object.Quay -> FragmentSelectionSet decodesTo EnturApi.Interface.PlaceInterface
onQuay (SelectionSet fields decoder) =
    FragmentSelectionSet "Quay" fields decoder


onBikeRentalStation : SelectionSet decodesTo EnturApi.Object.BikeRentalStation -> FragmentSelectionSet decodesTo EnturApi.Interface.PlaceInterface
onBikeRentalStation (SelectionSet fields decoder) =
    FragmentSelectionSet "BikeRentalStation" fields decoder


onBikePark : SelectionSet decodesTo EnturApi.Object.BikePark -> FragmentSelectionSet decodesTo EnturApi.Interface.PlaceInterface
onBikePark (SelectionSet fields decoder) =
    FragmentSelectionSet "BikePark" fields decoder


onCarPark : SelectionSet decodesTo EnturApi.Object.CarPark -> FragmentSelectionSet decodesTo EnturApi.Interface.PlaceInterface
onCarPark (SelectionSet fields decoder) =
    FragmentSelectionSet "CarPark" fields decoder


id : Field EnturApi.Scalar.Id EnturApi.Interface.PlaceInterface
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map EnturApi.Scalar.Id)


latitude : Field (Maybe Float) EnturApi.Interface.PlaceInterface
latitude =
    Object.fieldDecoder "latitude" [] (Decode.float |> Decode.nullable)


longitude : Field (Maybe Float) EnturApi.Interface.PlaceInterface
longitude =
    Object.fieldDecoder "longitude" [] (Decode.float |> Decode.nullable)
