-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.BookingArrangement exposing (bookWhen, bookingAccess, bookingContact, bookingMethods, bookingNote, buyWhen, latestBookingTime, minimumBookingPeriod, selection)

import EnturApi.Enum.BookingAccess
import EnturApi.Enum.BookingMethod
import EnturApi.Enum.PurchaseMoment
import EnturApi.Enum.PurchaseWhen
import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.BookingArrangement
selection constructor =
    Object.selection constructor


{-| Who has access to book service?
-}
bookingAccess : Field (Maybe EnturApi.Enum.BookingAccess.BookingAccess) EnturApi.Object.BookingArrangement
bookingAccess =
    Object.fieldDecoder "bookingAccess" [] (EnturApi.Enum.BookingAccess.decoder |> Decode.nullable)


{-| How should service be booked?
-}
bookingMethods : Field (Maybe (List (Maybe EnturApi.Enum.BookingMethod.BookingMethod))) EnturApi.Object.BookingArrangement
bookingMethods =
    Object.fieldDecoder "bookingMethods" [] (EnturApi.Enum.BookingMethod.decoder |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| When should service be booked?
-}
bookWhen : Field (Maybe EnturApi.Enum.PurchaseWhen.PurchaseWhen) EnturApi.Object.BookingArrangement
bookWhen =
    Object.fieldDecoder "bookWhen" [] (EnturApi.Enum.PurchaseWhen.decoder |> Decode.nullable)


{-| Latest time service can be booked. ISO 8601 timestamp
-}
latestBookingTime : Field (Maybe EnturApi.Scalar.LocalTime) EnturApi.Object.BookingArrangement
latestBookingTime =
    Object.fieldDecoder "latestBookingTime" [] (Object.scalarDecoder |> Decode.map EnturApi.Scalar.LocalTime |> Decode.nullable)


{-| Minimum period in advance service can be booked as a ISO 8601 duration
-}
minimumBookingPeriod : Field (Maybe String) EnturApi.Object.BookingArrangement
minimumBookingPeriod =
    Object.fieldDecoder "minimumBookingPeriod" [] (Decode.string |> Decode.nullable)


{-| Textual description of booking arrangement for service
-}
bookingNote : Field (Maybe String) EnturApi.Object.BookingArrangement
bookingNote =
    Object.fieldDecoder "bookingNote" [] (Decode.string |> Decode.nullable)


{-| When should ticket be purchased?
-}
buyWhen : Field (Maybe (List (Maybe EnturApi.Enum.PurchaseMoment.PurchaseMoment))) EnturApi.Object.BookingArrangement
buyWhen =
    Object.fieldDecoder "buyWhen" [] (EnturApi.Enum.PurchaseMoment.decoder |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Who should ticket be contacted for booking
-}
bookingContact : SelectionSet decodesTo EnturApi.Object.Contact -> Field (Maybe decodesTo) EnturApi.Object.BookingArrangement
bookingContact object_ =
    Object.selectionField "bookingContact" [] object_ (identity >> Decode.nullable)
