-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Contact exposing (contactPerson, email, furtherDetails, phone, selection, url)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.Contact
selection constructor =
    Object.selection constructor


{-| Name of person to contact
-}
contactPerson : Field (Maybe String) EnturApi.Object.Contact
contactPerson =
    Object.fieldDecoder "contactPerson" [] (Decode.string |> Decode.nullable)


{-| Email adress for contact
-}
email : Field (Maybe String) EnturApi.Object.Contact
email =
    Object.fieldDecoder "email" [] (Decode.string |> Decode.nullable)


{-| Url for contact
-}
url : Field (Maybe String) EnturApi.Object.Contact
url =
    Object.fieldDecoder "url" [] (Decode.string |> Decode.nullable)


{-| Phone number for contact
-}
phone : Field (Maybe String) EnturApi.Object.Contact
phone =
    Object.fieldDecoder "phone" [] (Decode.string |> Decode.nullable)


{-| Textual description of how to get in contact
-}
furtherDetails : Field (Maybe String) EnturApi.Object.Contact
furtherDetails =
    Object.fieldDecoder "furtherDetails" [] (Decode.string |> Decode.nullable)
