-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Line exposing (authority, bikesAllowed, bookingArrangements, description, flexibleLineType, id, journeyPatterns, keyValues, name, notices, operator, organisation, presentation, publicCode, quays, selection, serviceJourneys, situations, transportMode, transportSubmode, url)

import EnturApi.Enum.BikesAllowed
import EnturApi.Enum.FlexibleLineType
import EnturApi.Enum.TransportMode
import EnturApi.Enum.TransportSubmode
import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.Line
selection constructor =
    Object.selection constructor


id : Field EnturApi.Scalar.Id EnturApi.Object.Line
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map EnturApi.Scalar.Id)


authority : SelectionSet decodesTo EnturApi.Object.Authority -> Field (Maybe decodesTo) EnturApi.Object.Line
authority object_ =
    Object.selectionField "authority" [] object_ (identity >> Decode.nullable)


operator : SelectionSet decodesTo EnturApi.Object.Operator -> Field (Maybe decodesTo) EnturApi.Object.Line
operator object_ =
    Object.selectionField "operator" [] object_ (identity >> Decode.nullable)


organisation : SelectionSet decodesTo EnturApi.Object.Organisation -> Field (Maybe decodesTo) EnturApi.Object.Line
organisation object_ =
    Object.selectionField "organisation" [] object_ (identity >> Decode.nullable)


{-| Publicly announced code for line, differentiating it from other lines for the same operator.
-}
publicCode : Field (Maybe String) EnturApi.Object.Line
publicCode =
    Object.fieldDecoder "publicCode" [] (Decode.string |> Decode.nullable)


name : Field (Maybe String) EnturApi.Object.Line
name =
    Object.fieldDecoder "name" [] (Decode.string |> Decode.nullable)


transportMode : Field (Maybe EnturApi.Enum.TransportMode.TransportMode) EnturApi.Object.Line
transportMode =
    Object.fieldDecoder "transportMode" [] (EnturApi.Enum.TransportMode.decoder |> Decode.nullable)


transportSubmode : Field (Maybe EnturApi.Enum.TransportSubmode.TransportSubmode) EnturApi.Object.Line
transportSubmode =
    Object.fieldDecoder "transportSubmode" [] (EnturApi.Enum.TransportSubmode.decoder |> Decode.nullable)


description : Field (Maybe String) EnturApi.Object.Line
description =
    Object.fieldDecoder "description" [] (Decode.string |> Decode.nullable)


url : Field (Maybe String) EnturApi.Object.Line
url =
    Object.fieldDecoder "url" [] (Decode.string |> Decode.nullable)


presentation : SelectionSet decodesTo EnturApi.Object.Presentation -> Field (Maybe decodesTo) EnturApi.Object.Line
presentation object_ =
    Object.selectionField "presentation" [] object_ (identity >> Decode.nullable)


bikesAllowed : Field (Maybe EnturApi.Enum.BikesAllowed.BikesAllowed) EnturApi.Object.Line
bikesAllowed =
    Object.fieldDecoder "bikesAllowed" [] (EnturApi.Enum.BikesAllowed.decoder |> Decode.nullable)


journeyPatterns : SelectionSet decodesTo EnturApi.Object.JourneyPattern -> Field (Maybe (List (Maybe decodesTo))) EnturApi.Object.Line
journeyPatterns object_ =
    Object.selectionField "journeyPatterns" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


quays : SelectionSet decodesTo EnturApi.Object.Quay -> Field (List (Maybe decodesTo)) EnturApi.Object.Line
quays object_ =
    Object.selectionField "quays" [] object_ (identity >> Decode.nullable >> Decode.list)


serviceJourneys : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> Field (List (Maybe decodesTo)) EnturApi.Object.Line
serviceJourneys object_ =
    Object.selectionField "serviceJourneys" [] object_ (identity >> Decode.nullable >> Decode.list)


notices : SelectionSet decodesTo EnturApi.Object.Notice -> Field (List (Maybe decodesTo)) EnturApi.Object.Line
notices object_ =
    Object.selectionField "notices" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Get all situations active for the line
-}
situations : SelectionSet decodesTo EnturApi.Object.PtSituationElement -> Field (List (Maybe decodesTo)) EnturApi.Object.Line
situations object_ =
    Object.selectionField "situations" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| List of keyValue pairs for the line.
-}
keyValues : SelectionSet decodesTo EnturApi.Object.KeyValue -> Field (Maybe (List (Maybe decodesTo))) EnturApi.Object.Line
keyValues object_ =
    Object.selectionField "keyValues" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| Type of flexible line, or null if line is not flexible.
-}
flexibleLineType : Field (Maybe EnturApi.Enum.FlexibleLineType.FlexibleLineType) EnturApi.Object.Line
flexibleLineType =
    Object.fieldDecoder "flexibleLineType" [] (EnturApi.Enum.FlexibleLineType.decoder |> Decode.nullable)


{-| Booking arrangements for flexible line.
-}
bookingArrangements : SelectionSet decodesTo EnturApi.Object.BookingArrangement -> Field (Maybe decodesTo) EnturApi.Object.Line
bookingArrangements object_ =
    Object.selectionField "bookingArrangements" [] object_ (identity >> Decode.nullable)
