-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.Notice exposing (id, publicCode, selection, text)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.Notice
selection constructor =
    Object.selection constructor


id : Field (Maybe String) EnturApi.Object.Notice
id =
    Object.fieldDecoder "id" [] (Decode.string |> Decode.nullable)


text : Field (Maybe String) EnturApi.Object.Notice
text =
    Object.fieldDecoder "text" [] (Decode.string |> Decode.nullable)


publicCode : Field (Maybe String) EnturApi.Object.Notice
publicCode =
    Object.fieldDecoder "publicCode" [] (Decode.string |> Decode.nullable)
