-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.PathGuidance exposing (LegStepTextOptionalArguments, area, bogusName, distance, exit, heading, latitude, legStepText, longitude, relativeDirection, selection, stayOn, streetName)

import EnturApi.Enum.AbsoluteDirection
import EnturApi.Enum.Locale
import EnturApi.Enum.RelativeDirection
import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.PathGuidance
selection constructor =
    Object.selection constructor


{-| The distance in meters that this step takes.
-}
distance : Field (Maybe Float) EnturApi.Object.PathGuidance
distance =
    Object.fieldDecoder "distance" [] (Decode.float |> Decode.nullable)


{-| The relative direction of this step.
-}
relativeDirection : Field (Maybe EnturApi.Enum.RelativeDirection.RelativeDirection) EnturApi.Object.PathGuidance
relativeDirection =
    Object.fieldDecoder "relativeDirection" [] (EnturApi.Enum.RelativeDirection.decoder |> Decode.nullable)


{-| The name of the street.
-}
streetName : Field (Maybe String) EnturApi.Object.PathGuidance
streetName =
    Object.fieldDecoder "streetName" [] (Decode.string |> Decode.nullable)


{-| The absolute direction of this step.
-}
heading : Field (Maybe EnturApi.Enum.AbsoluteDirection.AbsoluteDirection) EnturApi.Object.PathGuidance
heading =
    Object.fieldDecoder "heading" [] (EnturApi.Enum.AbsoluteDirection.decoder |> Decode.nullable)


{-| When exiting a highway or traffic circle, the exit name/number.
-}
exit : Field (Maybe String) EnturApi.Object.PathGuidance
exit =
    Object.fieldDecoder "exit" [] (Decode.string |> Decode.nullable)


{-| Indicates whether or not a street changes direction at an intersection.
-}
stayOn : Field (Maybe Bool) EnturApi.Object.PathGuidance
stayOn =
    Object.fieldDecoder "stayOn" [] (Decode.bool |> Decode.nullable)


{-| This step is on an open area, such as a plaza or train platform, and thus the directions should say something like "cross"
-}
area : Field (Maybe Bool) EnturApi.Object.PathGuidance
area =
    Object.fieldDecoder "area" [] (Decode.bool |> Decode.nullable)


{-| The name of this street was generated by the system, so we should only display it once, and generally just display right/left directions
-}
bogusName : Field (Maybe Bool) EnturApi.Object.PathGuidance
bogusName =
    Object.fieldDecoder "bogusName" [] (Decode.bool |> Decode.nullable)


{-| The latitude of the step.
-}
latitude : Field (Maybe Float) EnturApi.Object.PathGuidance
latitude =
    Object.fieldDecoder "latitude" [] (Decode.float |> Decode.nullable)


{-| The longitude of the step.
-}
longitude : Field (Maybe Float) EnturApi.Object.PathGuidance
longitude =
    Object.fieldDecoder "longitude" [] (Decode.float |> Decode.nullable)


type alias LegStepTextOptionalArguments =
    { locale : OptionalArgument EnturApi.Enum.Locale.Locale }


{-| Direction information as readable text.
-}
legStepText : (LegStepTextOptionalArguments -> LegStepTextOptionalArguments) -> Field (Maybe String) EnturApi.Object.PathGuidance
legStepText fillInOptionals =
    let
        filledInOptionals =
            fillInOptionals { locale = Absent }

        optionalArgs =
            [ Argument.optional "locale" filledInOptionals.locale (Encode.enum EnturApi.Enum.Locale.toString) ]
                |> List.filterMap identity
    in
    Object.fieldDecoder "legStepText" optionalArgs (Decode.string |> Decode.nullable)
