-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.QuayAtDistance exposing (distance, id, quay, selection)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.QuayAtDistance
selection constructor =
    Object.selection constructor


id : Field EnturApi.Scalar.Id EnturApi.Object.QuayAtDistance
id =
    Object.fieldDecoder "id" [] (Object.scalarDecoder |> Decode.map EnturApi.Scalar.Id)


quay : SelectionSet decodesTo EnturApi.Object.Quay -> Field (Maybe decodesTo) EnturApi.Object.QuayAtDistance
quay object_ =
    Object.selectionField "quay" [] object_ (identity >> Decode.nullable)


distance : Field (Maybe Int) EnturApi.Object.QuayAtDistance
distance =
    Object.fieldDecoder "distance" [] (Decode.int |> Decode.nullable)
