-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.RoutingParameters exposing (alightSlack, allowBikeRental, bikeBoardCost, bikeParkAndRide, bikeParkCost, bikeParkTime, bikeRentalDropOffCost, bikeRentalDropOffTime, bikeRentalPickupCost, bikeRentalPickupTime, bikeSpeed, boardSlack, carAccelerationSpeed, carDecelerationSpeed, carDropOffTime, carSpeed, compactLegsByReversedSearch, disableAlertFiltering, disableRemainingWeightHeuristic, elevatorBoardCost, elevatorBoardTime, elevatorHopCost, elevatorHopTime, geoIdElevation, ignoreRealTimeUpdates, includedPlannedCancellations, interchangeAllowedPenalty, kissAndRide, maxPreTransitTime, maxSlope, maxTransferWalkDistance, maxTransfers, maxWalkDistance, noInterchangePenalty, numItineraries, onlyTransitTrips, otherThanPreferredRoutesPenalty, parkAndRide, preTransitOverageRate, preTransitPenalty, preTransitReluctance, preferredInterchangePenalty, recommendedInterchangePenalty, reverseOptimizeOnTheFly, rideAndKiss, selection, showIntermediateStops, softPreTransitLimiting, softWalkLimiting, softWalkOverageRate, softWalkPenalty, stairsReluctance, transferPenalty, transferSlack, turnReluctance, useTraffic, waitAtBeginningFactor, waitReluctance, walkBoardCost, walkOnStreetReluctance, walkReluctance, walkSpeed, wheelChairAccessible)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.RoutingParameters
selection constructor =
    Object.selection constructor


{-| Max walk speed along streets, in meters per second
-}
walkSpeed : Field (Maybe Float) EnturApi.Object.RoutingParameters
walkSpeed =
    Object.fieldDecoder "walkSpeed" [] (Decode.float |> Decode.nullable)


{-| Max bike speed along streets, in meters per second
-}
bikeSpeed : Field (Maybe Float) EnturApi.Object.RoutingParameters
bikeSpeed =
    Object.fieldDecoder "bikeSpeed" [] (Decode.float |> Decode.nullable)


{-| Max car speed along streets, in meters per second
-}
carSpeed : Field (Maybe Float) EnturApi.Object.RoutingParameters
carSpeed =
    Object.fieldDecoder "carSpeed" [] (Decode.float |> Decode.nullable)


{-| The maximum distance (in meters) the user is willing to walk for access/egress legs.
-}
maxWalkDistance : Field (Maybe Float) EnturApi.Object.RoutingParameters
maxWalkDistance =
    Object.fieldDecoder "maxWalkDistance" [] (Decode.float |> Decode.nullable)


{-| The maximum distance (in meters) the user is willing to walk for transfer legs.
-}
maxTransferWalkDistance : Field (Maybe Float) EnturApi.Object.RoutingParameters
maxTransferWalkDistance =
    Object.fieldDecoder "maxTransferWalkDistance" [] (Decode.float |> Decode.nullable)


{-| The maximum time (in seconds) of pre-transit travel when using drive-to-transit (park and ride or kiss and ride).
-}
maxPreTransitTime : Field (Maybe Float) EnturApi.Object.RoutingParameters
maxPreTransitTime =
    Object.fieldDecoder "maxPreTransitTime" [] (Decode.float |> Decode.nullable)


{-| Whether the trip must be wheelchair accessible.
-}
wheelChairAccessible : Field (Maybe Bool) EnturApi.Object.RoutingParameters
wheelChairAccessible =
    Object.fieldDecoder "wheelChairAccessible" [] (Decode.bool |> Decode.nullable)


{-| The maximum number of itineraries to return.
-}
numItineraries : Field (Maybe Int) EnturApi.Object.RoutingParameters
numItineraries =
    Object.fieldDecoder "numItineraries" [] (Decode.int |> Decode.nullable)


{-| The maximum slope of streets for wheelchair trips.
-}
maxSlope : Field (Maybe Float) EnturApi.Object.RoutingParameters
maxSlope =
    Object.fieldDecoder "maxSlope" [] (Decode.float |> Decode.nullable)


{-| Whether the planner should return intermediate stops lists for transit legs.
-}
showIntermediateStops : Field (Maybe Bool) EnturApi.Object.RoutingParameters
showIntermediateStops =
    Object.fieldDecoder "showIntermediateStops" [] (Decode.bool |> Decode.nullable)


{-| An extra penalty added on transfers (i.e. all boardings except the first one).
-}
transferPenalty : Field (Maybe Int) EnturApi.Object.RoutingParameters
transferPenalty =
    Object.fieldDecoder "transferPenalty" [] (Decode.int |> Decode.nullable)


{-| A multiplier for how bad walking is, compared to being in transit for equal lengths of time.
-}
walkReluctance : Field (Maybe Float) EnturApi.Object.RoutingParameters
walkReluctance =
    Object.fieldDecoder "walkReluctance" [] (Decode.float |> Decode.nullable)


{-| Used instead of walkReluctance for stairs.
-}
stairsReluctance : Field (Maybe Float) EnturApi.Object.RoutingParameters
stairsReluctance =
    Object.fieldDecoder "stairsReluctance" [] (Decode.float |> Decode.nullable)


{-| Multiplicative factor on expected turning time.
-}
turnReluctance : Field (Maybe Float) EnturApi.Object.RoutingParameters
turnReluctance =
    Object.fieldDecoder "turnReluctance" [] (Decode.float |> Decode.nullable)


{-| How much more reluctant is the user to walk on streets with car traffic allowed.
-}
walkOnStreetReluctance : Field (Maybe Float) EnturApi.Object.RoutingParameters
walkOnStreetReluctance =
    Object.fieldDecoder "walkOnStreetReluctance" [] (Decode.float |> Decode.nullable)


{-| How long does it take to get on an elevator, on average.
-}
elevatorBoardTime : Field (Maybe Int) EnturApi.Object.RoutingParameters
elevatorBoardTime =
    Object.fieldDecoder "elevatorBoardTime" [] (Decode.int |> Decode.nullable)


{-| What is the cost of boarding a elevator?
-}
elevatorBoardCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
elevatorBoardCost =
    Object.fieldDecoder "elevatorBoardCost" [] (Decode.int |> Decode.nullable)


{-| How long does it take to advance one floor on an elevator?
-}
elevatorHopTime : Field (Maybe Int) EnturApi.Object.RoutingParameters
elevatorHopTime =
    Object.fieldDecoder "elevatorHopTime" [] (Decode.int |> Decode.nullable)


{-| What is the cost of travelling one floor on an elevator?
-}
elevatorHopCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
elevatorHopCost =
    Object.fieldDecoder "elevatorHopCost" [] (Decode.int |> Decode.nullable)


{-| Time to rent a bike.
-}
bikeRentalPickupTime : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalPickupTime =
    Object.fieldDecoder "bikeRentalPickupTime" [] (Decode.int |> Decode.nullable)


{-| Cost to rent a bike.
-}
bikeRentalPickupCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalPickupCost =
    Object.fieldDecoder "bikeRentalPickupCost" [] (Decode.int |> Decode.nullable)


{-| Time to drop-off a rented bike.
-}
bikeRentalDropOffTime : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalDropOffTime =
    Object.fieldDecoder "bikeRentalDropOffTime" [] (Decode.int |> Decode.nullable)


{-| Cost to drop-off a rented bike.
-}
bikeRentalDropOffCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeRentalDropOffCost =
    Object.fieldDecoder "bikeRentalDropOffCost" [] (Decode.int |> Decode.nullable)


{-| Time to park a bike.
-}
bikeParkTime : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeParkTime =
    Object.fieldDecoder "bikeParkTime" [] (Decode.int |> Decode.nullable)


{-| Cost to park a bike.
-}
bikeParkCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeParkCost =
    Object.fieldDecoder "bikeParkCost" [] (Decode.int |> Decode.nullable)


{-| Time to park a car in a park and ride, w/o taking into account driving and walking cost.
-}
carDropOffTime : Field (Maybe Int) EnturApi.Object.RoutingParameters
carDropOffTime =
    Object.fieldDecoder "carDropOffTime" [] (Decode.int |> Decode.nullable)


{-| How much worse is waiting for a transit vehicle than being on a transit vehicle, as a multiplier.
-}
waitReluctance : Field (Maybe Float) EnturApi.Object.RoutingParameters
waitReluctance =
    Object.fieldDecoder "waitReluctance" [] (Decode.float |> Decode.nullable)


{-| How much less bad is waiting at the beginning of the trip (replaces waitReluctance on the first boarding).
-}
waitAtBeginningFactor : Field (Maybe Float) EnturApi.Object.RoutingParameters
waitAtBeginningFactor =
    Object.fieldDecoder "waitAtBeginningFactor" [] (Decode.float |> Decode.nullable)


{-| This prevents unnecessary transfers by adding a cost for boarding a vehicle.
-}
walkBoardCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
walkBoardCost =
    Object.fieldDecoder "walkBoardCost" [] (Decode.int |> Decode.nullable)


{-| Separate cost for boarding a vehicle with a bicycle, which is more difficult than on foot.
-}
bikeBoardCost : Field (Maybe Int) EnturApi.Object.RoutingParameters
bikeBoardCost =
    Object.fieldDecoder "bikeBoardCost" [] (Decode.int |> Decode.nullable)


{-| Penalty added for using every route that is not preferred if user set any route as preferred. We return number of seconds that we are willing to wait for preferred route.
-}
otherThanPreferredRoutesPenalty : Field (Maybe Int) EnturApi.Object.RoutingParameters
otherThanPreferredRoutesPenalty =
    Object.fieldDecoder "otherThanPreferredRoutesPenalty" [] (Decode.int |> Decode.nullable)


{-| A global minimum transfer time (in seconds) that specifies the minimum amount of time that must pass between exiting one transit vehicle and boarding another.
-}
transferSlack : Field (Maybe Int) EnturApi.Object.RoutingParameters
transferSlack =
    Object.fieldDecoder "transferSlack" [] (Decode.int |> Decode.nullable)


{-| Invariant: boardSlack + alightSlack <= transferSlack.
-}
boardSlack : Field (Maybe Int) EnturApi.Object.RoutingParameters
boardSlack =
    Object.fieldDecoder "boardSlack" [] (Decode.int |> Decode.nullable)


{-| Invariant: boardSlack + alightSlack <= transferSlack.
-}
alightSlack : Field (Maybe Int) EnturApi.Object.RoutingParameters
alightSlack =
    Object.fieldDecoder "alightSlack" [] (Decode.int |> Decode.nullable)


{-| Maximum number of transfers returned in a trip plan.
-}
maxTransfers : Field (Maybe Int) EnturApi.Object.RoutingParameters
maxTransfers =
    Object.fieldDecoder "maxTransfers" [] (Decode.int |> Decode.nullable)


{-| When true, reverse optimize this search on the fly whenever needed, rather than reverse-optimizing the entire path when it's done.
-}
reverseOptimizeOnTheFly : Field (Maybe Bool) EnturApi.Object.RoutingParameters
reverseOptimizeOnTheFly =
    Object.fieldDecoder "reverseOptimizeOnTheFly" [] (Decode.bool |> Decode.nullable)


{-| When true, do a full reversed search to compact the legs of the GraphPath.
-}
compactLegsByReversedSearch : Field (Maybe Bool) EnturApi.Object.RoutingParameters
compactLegsByReversedSearch =
    Object.fieldDecoder "compactLegsByReversedSearch" [] (Decode.bool |> Decode.nullable)


{-| The deceleration speed of an automobile, in meters per second per second.
-}
carDecelerationSpeed : Field (Maybe Float) EnturApi.Object.RoutingParameters
carDecelerationSpeed =
    Object.fieldDecoder "carDecelerationSpeed" [] (Decode.float |> Decode.nullable)


{-| The acceleration speed of an automobile, in meters per second per second.
-}
carAccelerationSpeed : Field (Maybe Float) EnturApi.Object.RoutingParameters
carAccelerationSpeed =
    Object.fieldDecoder "carAccelerationSpeed" [] (Decode.float |> Decode.nullable)


{-| When true, realtime updates are ignored during this search.
-}
ignoreRealTimeUpdates : Field (Maybe Bool) EnturApi.Object.RoutingParameters
ignoreRealTimeUpdates =
    Object.fieldDecoder "ignoreRealTimeUpdates" [] (Decode.bool |> Decode.nullable)


{-| When true, service journeys cancelled in scheduled route data will be included during this search.
-}
includedPlannedCancellations : Field (Maybe Bool) EnturApi.Object.RoutingParameters
includedPlannedCancellations =
    Object.fieldDecoder "includedPlannedCancellations" [] (Decode.bool |> Decode.nullable)


{-| If true, the remaining weight heuristic is disabled.
-}
disableRemainingWeightHeuristic : Field (Maybe Bool) EnturApi.Object.RoutingParameters
disableRemainingWeightHeuristic =
    Object.fieldDecoder "disableRemainingWeightHeuristic" [] (Decode.bool |> Decode.nullable)


softWalkLimiting : Field (Maybe Bool) EnturApi.Object.RoutingParameters
softWalkLimiting =
    Object.fieldDecoder "softWalkLimiting" [] (Decode.bool |> Decode.nullable)


softPreTransitLimiting : Field (Maybe Bool) EnturApi.Object.RoutingParameters
softPreTransitLimiting =
    Object.fieldDecoder "softPreTransitLimiting" [] (Decode.bool |> Decode.nullable)


{-| A jump in cost when stepping over the walking limit.
-}
softWalkPenalty : Field (Maybe Float) EnturApi.Object.RoutingParameters
softWalkPenalty =
    Object.fieldDecoder "softWalkPenalty" [] (Decode.float |> Decode.nullable)


{-| A jump in cost for every meter over the walking limit.
-}
softWalkOverageRate : Field (Maybe Float) EnturApi.Object.RoutingParameters
softWalkOverageRate =
    Object.fieldDecoder "softWalkOverageRate" [] (Decode.float |> Decode.nullable)


{-| A jump in cost when stepping over the pre-transit time limit.
-}
preTransitPenalty : Field (Maybe Float) EnturApi.Object.RoutingParameters
preTransitPenalty =
    Object.fieldDecoder "preTransitPenalty" [] (Decode.float |> Decode.nullable)


{-| A jump in cost for every second over the pre-transit time limit.
-}
preTransitOverageRate : Field (Maybe Float) EnturApi.Object.RoutingParameters
preTransitOverageRate =
    Object.fieldDecoder "preTransitOverageRate" [] (Decode.float |> Decode.nullable)


{-| -}
allowBikeRental : Field (Maybe Bool) EnturApi.Object.RoutingParameters
allowBikeRental =
    Object.fieldDecoder "allowBikeRental" [] (Decode.bool |> Decode.nullable)


bikeParkAndRide : Field (Maybe Bool) EnturApi.Object.RoutingParameters
bikeParkAndRide =
    Object.fieldDecoder "bikeParkAndRide" [] (Decode.bool |> Decode.nullable)


parkAndRide : Field (Maybe Bool) EnturApi.Object.RoutingParameters
parkAndRide =
    Object.fieldDecoder "parkAndRide" [] (Decode.bool |> Decode.nullable)


kissAndRide : Field (Maybe Bool) EnturApi.Object.RoutingParameters
kissAndRide =
    Object.fieldDecoder "kissAndRide" [] (Decode.bool |> Decode.nullable)


rideAndKiss : Field (Maybe Bool) EnturApi.Object.RoutingParameters
rideAndKiss =
    Object.fieldDecoder "rideAndKiss" [] (Decode.bool |> Decode.nullable)


{-| Should traffic congestion be considered when driving?
-}
useTraffic : Field (Maybe Bool) EnturApi.Object.RoutingParameters
useTraffic =
    Object.fieldDecoder "useTraffic" [] (Decode.bool |> Decode.nullable)


{-| Accept only paths that use transit (no street-only paths).
-}
onlyTransitTrips : Field (Maybe Bool) EnturApi.Object.RoutingParameters
onlyTransitTrips =
    Object.fieldDecoder "onlyTransitTrips" [] (Decode.bool |> Decode.nullable)


{-| Option to disable the default filtering of GTFS-RT alerts by time.
-}
disableAlertFiltering : Field (Maybe Bool) EnturApi.Object.RoutingParameters
disableAlertFiltering =
    Object.fieldDecoder "disableAlertFiltering" [] (Decode.bool |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
geoIdElevation : Field (Maybe Bool) EnturApi.Object.RoutingParameters
geoIdElevation =
    Object.fieldDecoder "geoIdElevation" [] (Decode.bool |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
preferredInterchangePenalty : Field (Maybe Int) EnturApi.Object.RoutingParameters
preferredInterchangePenalty =
    Object.fieldDecoder "preferredInterchangePenalty" [] (Decode.int |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
recommendedInterchangePenalty : Field (Maybe Int) EnturApi.Object.RoutingParameters
recommendedInterchangePenalty =
    Object.fieldDecoder "recommendedInterchangePenalty" [] (Decode.int |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
interchangeAllowedPenalty : Field (Maybe Int) EnturApi.Object.RoutingParameters
interchangeAllowedPenalty =
    Object.fieldDecoder "interchangeAllowedPenalty" [] (Decode.int |> Decode.nullable)


{-| Whether to apply the ellipsoid->geoid offset to all elevations in the response.
-}
noInterchangePenalty : Field (Maybe Int) EnturApi.Object.RoutingParameters
noInterchangePenalty =
    Object.fieldDecoder "noInterchangePenalty" [] (Decode.int |> Decode.nullable)


{-| How much worse driving before and after transit is than riding on transit. Applies to ride and kiss, kiss and ride and park and ride.
-}
preTransitReluctance : Field (Maybe Float) EnturApi.Object.RoutingParameters
preTransitReluctance =
    Object.fieldDecoder "preTransitReluctance" [] (Decode.float |> Decode.nullable)
