-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Object.TimetabledPassingTime exposing (arrival, bookingArrangements, departure, destinationDisplay, forAlighting, forBoarding, notices, quay, requestStop, selection, serviceJourney, timingPoint)

import EnturApi.InputObject
import EnturApi.Interface
import EnturApi.Object
import EnturApi.Scalar
import EnturApi.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) EnturApi.Object.TimetabledPassingTime
selection constructor =
    Object.selection constructor


quay : SelectionSet decodesTo EnturApi.Object.Quay -> Field (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
quay object_ =
    Object.selectionField "quay" [] object_ (identity >> Decode.nullable)


{-| Scheduled time of arrival at quay
-}
arrival : SelectionSet decodesTo EnturApi.Object.TimeAndDayOffset -> Field (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
arrival object_ =
    Object.selectionField "arrival" [] object_ (identity >> Decode.nullable)


{-| Scheduled time of departure from quay
-}
departure : SelectionSet decodesTo EnturApi.Object.TimeAndDayOffset -> Field (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
departure object_ =
    Object.selectionField "departure" [] object_ (identity >> Decode.nullable)


{-| Whether this is a timing point or not. Boarding and alighting is not allowed at timing points.
-}
timingPoint : Field (Maybe Bool) EnturApi.Object.TimetabledPassingTime
timingPoint =
    Object.fieldDecoder "timingPoint" [] (Decode.bool |> Decode.nullable)


{-| Whether vehicle may be boarded at quay.
-}
forBoarding : Field (Maybe Bool) EnturApi.Object.TimetabledPassingTime
forBoarding =
    Object.fieldDecoder "forBoarding" [] (Decode.bool |> Decode.nullable)


{-| Whether vehicle may be alighted at quay.
-}
forAlighting : Field (Maybe Bool) EnturApi.Object.TimetabledPassingTime
forAlighting =
    Object.fieldDecoder "forAlighting" [] (Decode.bool |> Decode.nullable)


{-| Whether vehicle will only stop on request.
-}
requestStop : Field (Maybe Bool) EnturApi.Object.TimetabledPassingTime
requestStop =
    Object.fieldDecoder "requestStop" [] (Decode.bool |> Decode.nullable)


serviceJourney : SelectionSet decodesTo EnturApi.Object.ServiceJourney -> Field (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
serviceJourney object_ =
    Object.selectionField "serviceJourney" [] object_ (identity >> Decode.nullable)


destinationDisplay : SelectionSet decodesTo EnturApi.Object.DestinationDisplay -> Field (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
destinationDisplay object_ =
    Object.selectionField "destinationDisplay" [] object_ (identity >> Decode.nullable)


notices : SelectionSet decodesTo EnturApi.Object.Notice -> Field (List (Maybe decodesTo)) EnturApi.Object.TimetabledPassingTime
notices object_ =
    Object.selectionField "notices" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| Booking arrangements for flexible service.
-}
bookingArrangements : SelectionSet decodesTo EnturApi.Object.BookingArrangement -> Field (Maybe decodesTo) EnturApi.Object.TimetabledPassingTime
bookingArrangements object_ =
    Object.selectionField "bookingArrangements" [] object_ (identity >> Decode.nullable)
