-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Enum.Locale exposing (Locale(..), decoder, toString)

import Json.Decode as Decode exposing (Decoder)


type Locale
    = No
    | Us


decoder : Decoder Locale
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "no" ->
                        Decode.succeed No

                    "us" ->
                        Decode.succeed Us

                    _ ->
                        Decode.fail ("Invalid Locale type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Locale -> String
toString enum =
    case enum of
        No ->
            "no"

        Us ->
            "us"
