-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module EnturApi.Enum.ServiceAlteration exposing (ServiceAlteration(..), decoder, toString)

import Json.Decode as Decode exposing (Decoder)


type ServiceAlteration
    = Planned
    | Cancellation
    | ExtraJourney


decoder : Decoder ServiceAlteration
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "planned" ->
                        Decode.succeed Planned

                    "cancellation" ->
                        Decode.succeed Cancellation

                    "extraJourney" ->
                        Decode.succeed ExtraJourney

                    _ ->
                        Decode.fail ("Invalid ServiceAlteration type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ServiceAlteration -> String
toString enum =
    case enum of
        Planned ->
            "planned"

        Cancellation ->
            "cancellation"

        ExtraJourney ->
            "extraJourney"
